config/routes.rb
Rails.application.routes.draw do
  # Devise routes for Admin and Customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :customers

  # Active Admin routes
  ActiveAdmin.routes(self)

  # Set the root to the products index page
  root 'products#index'

  # Product routes with nested cart management routes
  resources :products, only: [:index, :show] do
    member do
      post 'add_to_cart', to: 'products#add_to_cart'
    end
  end

  # Profile routes for a singular resource
  resource :profile, only: [:show, :edit, :update]

  # Cart routes
  get '/cart', to: 'carts#show', as: 'cart'
  delete '/cart/remove/:product_id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
  patch '/cart/update/:product_id', to: 'carts#update_cart_item', as: 'update_cart_item'

  # Routes for orders, including the new order form
  resources :orders, only: [:new, :create]

  # Custom route for initiating checkout
  get '/initiate_checkout', to: 'carts#initiate_checkout', as: 'initiate_checkout'

  # Route for calculating taxes
  get '/calculate_taxes/:province_id', to: 'orders#calculate_taxes', as: 'calculate_taxes'

  # For webhooks with stripe
  post 'webhooks/stripe', to: 'webhooks#stripe'

  # Route for the PaymentsController create action
  post 'payments', to: 'payments#create', as: 'payments'

  # If you have success and cancel actions
  get 'payments/success', to: 'payments#success', as: 'payments_success'
  get 'payments/cancel', to: 'payments#cancel', as: 'payments_cancel'

  get '/users/:id', to: 'users#show', as: 'user_profile'

  # config/routes.rb
get 'lidar', to: 'lidars#show'


# config/routes.rb
get 'lidar_viewer/:file_name', to: 'lidars#viewer', as: 'lidar_viewer'


  # Resourceful routes for customers with an additional collection route
  resources :customers do
    collection do
      get 'alphabetized'
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CartManagement

  def show
    @cart_items = session[:cart] || []
    @total_price = @cart_items.empty? ? 0 : calculate_total_price
  end

  def initiate_checkout
    if customer_signed_in?
      # Assuming you have an order creation path or a checkout summary page
      redirect_to new_order_path # Replace with your actual new order path
    else
      # Store the intended path for checkout to redirect after sign-in
      session[:checkout_path] = new_order_path # Replace with your actual new order path
      flash[:alert] = 'Please sign in or sign up to complete your purchase'
      redirect_to new_customer_session_path
    end
  end





  def update_cart_item
    product_id = params[:product_id].to_i
    new_quantity = params[:quantity].to_i

    # Update the quantity of the specified product in the cart
    update_cart(product_id, new_quantity)

    redirect_to cart_path, notice: 'Cart updated successfully.'
  end

  def remove_from_cart
    product_id = params[:product_id].to_i

    # Remove the specified product from the cart
    remove_product_from_cart(product_id)

    redirect_to cart_path, notice: 'Item removed from cart.'
  end

  private



  # You could use this method as a before_action filter if needed
  def store_checkout_path
    session[:checkout_path] = new_order_path # Replace with your actual new order path
  end

  private


  def update_cart(product_id, new_quantity)
    session[:cart].each do |item|
      if item["product_id"] == product_id
        item["quantity"] = new_quantity
        break
      end
    end
  end

  def remove_product_from_cart(product_id)
    session[:cart].delete_if { |item| item["product_id"] == product_id }
  end
end

  def calculate_total_price
    session[:cart].sum do |item|
      product = Product.find(item["product_id"])
      product.price * item["quantity"]
    end
  end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<!-- views/carts/show.html.erb -->
<section class="section">
  <div class="container">
    <h1 class="title">Your Cart</h1>

    <% if session[:cart].empty? %>
    <p class="empty-cart-message">Your cart is empty.</p>
    <% else %>
      <table class="table is-fullwidth is-striped">
        <thead>
          <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% session[:cart].each do |item| %>
            <% product = Product.find(item["product_id"]) %>
            <tr>
              <td><%= product.name %></td>
              <td>
                <%= form_with url: update_cart_item_path(product_id: product.id), method: :patch, class: 'form' do |f| %>
                  <div class="field has-addons">
                    <div class="control">
                      <%= f.number_field :quantity, value: item["quantity"], min: 0, max: product.quantity_available, step: 1, class: 'input' %>
                    </div>
                    <div class="control">
                      <%= f.submit "Update", class: "button is-info" %>
                    </div>
                  </div>
                <% end %>
              </td>
              <td>
                <%= link_to 'Remove', remove_from_cart_path(product_id: product.id), method: :delete, class: 'button is-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <p class="is-size-4 total-price-text">Total Price: <%= number_to_currency(@total_price) %></p>


      <%= link_to 'Checkout', initiate_checkout_path, class: 'button is-primary is-large' %>
    <% end %>
  </div>
</section>