config/routes.rb
Rails.application.routes.draw do
  # Devise routes for Admin and Customers
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :customers

  # Active Admin routes
  ActiveAdmin.routes(self)

  # Set the root to the products index page
  root 'products#index'

  # Product routes with nested cart management routes
  resources :products, only: [:index, :show] do
    member do
      post 'add_to_cart', to: 'products#add_to_cart'
    end
  end

  # Profile routes for a singular resource
  resource :profile, only: [:show, :edit, :update]

  # Cart routes
  get '/cart', to: 'carts#show', as: 'cart'
  delete '/cart/remove/:product_id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
  patch '/cart/update/:product_id', to: 'carts#update_cart_item', as: 'update_cart_item'

  # Routes for orders, including the new order form
  resources :orders, only: [:new, :create]

  # Custom route for initiating checkout
  get '/initiate_checkout', to: 'carts#initiate_checkout', as: 'initiate_checkout'

  # Route for calculating taxes
  get '/calculate_taxes/:province_id', to: 'orders#calculate_taxes', as: 'calculate_taxes'

  # For webhooks with stripe
  post 'webhooks/stripe', to: 'webhooks#stripe'

  # Route for the PaymentsController create action
  post 'payments', to: 'payments#create', as: 'payments'

  # If you have success and cancel actions
  get 'payments/success', to: 'payments#success', as: 'payments_success'
  get 'payments/cancel', to: 'payments#cancel', as: 'payments_cancel'

  get '/users/:id', to: 'users#show', as: 'user_profile'

  # config/routes.rb
get 'lidar', to: 'lidars#show'


# config/routes.rb
get 'lidar_viewer/:file_name', to: 'lidars#viewer', as: 'lidar_viewer'


  # Resourceful routes for customers with an additional collection route
  resources :customers do
    collection do
      get 'alphabetized'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # Relationships
  belongs_to :category
  has_many_attached :images
  has_many :order_products

  # Validations
  validates :quantity_available, numericality: { greater_than_or_equal_to: 0 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  # Method to return the price in cents for Stripe
  def price_in_cents
    (price * 100).to_i
  end

  # Method to return the URL of the main product image
  def main_image_url
    images.attached? ? Rails.application.routes.url_helpers.url_for(images.first) : nil
  end

  # Check if product can be deleted
  def can_be_deleted?
    order_products.empty?
  end

  # Searchable attributes for Ransack
  def self.ransackable_attributes(auth_object = nil)
    %w[name description price category_id]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include CartManagement
  before_action :set_product, only: [:show, :destroy]
  before_action :set_user_dashboard, only: [:index]

  def index
    @products = params[:category_id].present? ? Product.where(category_id: params[:category_id]) : Product.all

    if params[:keyword].present?
      @products = @products.where('name LIKE :keyword OR description LIKE :keyword', keyword: "%#{params[:keyword]}%")
    end

    @products = @products.with_attached_images.page(params[:page]).per(10)
  end

  def show
    # @product is set by the set_product before_action
  end

  def add_to_cart
    quantity = params[:quantity].to_i
    product = Product.find_by(id: params[:product_id])

    if product.nil? || quantity <= 0 || quantity > product.quantity_available
      redirect_to product_path(product), alert: 'Invalid quantity or product not available.'
      return
    end

    session[:cart] << { "product_id" => product.id, "quantity" => quantity }
    redirect_to products_path, notice: 'Product added to cart!'
  end

  def destroy
    if @product.can_be_deleted?
      @product.destroy
      redirect_to products_path, notice: 'Product was successfully deleted.'
    else
      redirect_to products_path, alert: 'Product cannot be deleted as it is part of an existing order.'
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def set_user_dashboard
    if customer_signed_in?
      @customer_dashboard_info = {
        email: current_customer.email,
        recent_orders: current_customer.orders.last(5)
      }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<!-- app/views/products/index.html.erb -->

<div class="columns" style="min-height: 100vh;">

  <!-- Sidebar with Filter Form -->
 <div class="column is-2" style="background: radial-gradient(#424242, #8e8e8e); display: flex; flex-direction: row;">
<%# <div class="column is-2" style="background: linear-gradient(to right, #f50057, rgba(245, 0, 87, 0)); display: flex; flex-direction: column;"> %>
<%# <div class="column is-2" style="background: linear-gradient(to right, colorStart, colorEnd); display: flex; flex-direction: column;"> %>

    <aside class="menu" style="flex-grow: 1; display: flex; flex-direction: column;">
      <div style="padding: 0.75rem;">
        <p class="menu-label" style="color: #8e8e8e;">
          Filter Products
        </p>
        <div class="menu-list">
      <%= form_with(url: products_path, method: :get, local: true, class: 'form') do |form| %>
      <div class="field">
      <%= form.label :category_id, "Choose a category:", class: 'label' %>
      <div class="control">
        <%= form.collection_select(:category_id, Category.all, :id, :name, { prompt: 'All Products' }, { class: 'select' }) %>
      </div>
        </div>
            <div class="field">
              <div class="control">
                <%= form.submit "Filter", class: 'button is-link' %>
              </div>
            </div>
          <% end %>

                 <!-- Search Form -->
        <div class="column is-one-third has-text-centered">
          <%= render 'partials/search' %>
        </div>
        <!-- cart button -->
       <%= link_to "See Cart", cart_path, class: 'button is-primary custom-cart-button' %>

        </div>
      </div>
      <div style="flex-grow: 1;"></div>
    </aside>
  </div>

  <!-- Main Content Column -->
  <div class="column is-three-fourths">

    <!-- Customer Dashboard and Authentication Button Section -->
    <% if customer_signed_in? %>
      <div class="columns is-vcentered is-mobile" style="background-color: #202020; color: #f5558e;">
        <!-- Title -->
      <div class="column is-one-third">
       <h1 class="title custom-dashboard-title">Customer Dashboard</h1>
      </div>
        <!--  profile  -->
        <div class="column is-one-third has-text-right">
          <%= link_to 'Profile', profile_path, class: 'button is-primary custom-profile-button' %>
        <!-- Greeting  -->
          <p class="hello-message custom-hello-message">Hello, <%= current_customer.email %></p>
           <!-- Logout  -->
        <%= link_to 'Logout', destroy_customer_session_path, method: :delete, class: 'button is-primary custom-logout-button' %>

        <!-- View LiDAR Button -->
      <%= link_to 'View LiDAR', lidar_path, class: 'button is-primary custom-lidar-button' %>

        </div>
      </div>
    <% else %>
      <div class="columns is-vcentered is-mobile">
        <!-- Title -->
        <div class="column is-one-third">
          <h1 class="title">Welcome to Our Store</h1>
        </div>
        <!-- Search Form Placeholder (empty column to balance the layout) -->
        <div class="column is-one-third"></div>
        <!-- Login -->
        <div class="column is-one-third has-text-right">
          <%= link_to 'Login', new_customer_session_path, class: 'button is-primary custom-login-button' %>
        </div>
      </div>
    <% end %>


    <!-- Products Listing Section -->
    <h2 class="title">Our Products</h2>
    <div class="columns is-multiline">
      <% @products.each do |product| %>
        <div class="custom-column-5">
          <div class="card">
            <div class="card-content">
              <%= link_to product.name, product_path(product), class: 'product-name title is-5' %>
              <% if product.images.attached? %>
                <% product.images.each do |image| %>
                  <figure class="image is-4by3">
                    <%= image_tag(image, class: "is-rounded") %>
                  </figure>
                <% end %>
              <% end %>
              <p class="subtitle is-6"><%= number_to_currency(product.price) %></p>
              <!-- Add to Cart Form -->
              <%= form_with(url: add_to_cart_product_path(product), method: :post, local: true) do |f| %>
                <%= hidden_field_tag :product_id, product.id %>
                <div class="field has-addons">
                  <div class="control">
                    <%= number_field_tag :quantity, 1, min: 1, class: 'input', style: 'width: 60px;' %>
                  </div>
                  <div class="control">
                    <%= submit_tag 'Add to Cart', class: 'button is-small is-primary' %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <!-- Pagination Links -->
    <div class="pagination-wrapper" style="text-align: center;">
      <%= paginate @products, theme: 'bulma' %>
    </div>

  </div>

</div>

app/views/products/show.html.erb
<div class="product-details">
  <h1><%= @product.name %></h1>
  <p><%= @product.description %></p>
  <p>Price: <%= number_to_currency(@product.price) %></p>

  <div class="product-images">
    <% @product.images.each do |image| %>
      <%= image_tag(image, size: "300x300") %>
    <% end %>
  </div>
</div>
<!-- app/views/products/show.html.erb -->
<%= link_to 'Back to Products', products_path %>